botbase/blueprints/chat.py
import os

from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request, current_app, Blueprint, send_from_directory, send_file
from flask_login import login_required, current_user

# from botbase.models import User, Project, Bot
# from botbase.forms import ProjectForm, BotForm, ProjectConfigForm
# from botbase.extensions import db
# from botbase.utils.flask_tool import redirect_back
# from botbase.utils.create_bot import create_qa_bot
# from botbase.decorators import admin_required, only_owner_can

chat_bp = Blueprint('chat', __name__)

@chat_bp.route('/<int:project_id>')
def chat(project_id):
    return render_template('chat/chat.html')

botbase/blueprints/project.py
import os

from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request, current_app, Blueprint, send_from_directory, send_file
from flask_login import login_required, current_user

from botbase.models import User, Project, Bot
from botbase.forms import ProjectForm, BotForm, ProjectConfigForm
from botbase.extensions import db
from botbase.utils.flask_tool import redirect_back
from botbase.utils.create_bot import create_qa_bot
from botbase.decorators import admin_required, only_owner_can

project_bp = Blueprint('project', __name__)

@project_bp.route('/<int:project_id>/index')
@only_owner_can
@login_required
def index(project_id):
    bots = Bot.query.filter_by(user_id=current_user.id).all()
    return render_template('project/index.html', project_id=project_id, bots=bots)

@project_bp.route('<int:project_id>/create_bot', methods=['GET', 'POST'])
@only_owner_can
@login_required
def create_bot(project_id):
    form = BotForm()
    if form.validate_on_submit():
        name = form.name.data 
        bot_type = form.bot_type.data
        lang = form.lang.data
        bot = Bot(
            name=name,
            bot_type=bot_type,
            lang=lang,
            project_id=project_id,
            user_id=current_user.id
        )
        db.session.add(bot)
        db.session.commit()
        if bot_type == 1:
            create_qa_bot(bot.id)
        flash('ChatBot添加完毕', 'info')
        return redirect(url_for('project.index', project_id=project_id))
    return render_template('project/create_bot.html', form=form, project_id=project_id)

@project_bp.route('/<int:project_id>/<int:bot_id>/delete', methods=['POST'])
@only_owner_can
@login_required
def delete_bot(project_id, bot_id):
    bot = Bot.query.get_or_404(bot_id)
    db.session.delete(bot)
    db.session.commit()
    flash('Bot deleted.', 'success')
    return redirect_back()

@project_bp.route('<int:project_id>/project_config', methods=['GET', 'POST'])
@only_owner_can
@login_required
def config(project_id):
    project = Project.query.get_or_404(project_id)
    form = ProjectConfigForm(
        name = project.name,
        welcome=project.welcome,
        unknown=project.unknown
    )

    if form.validate_on_submit():
        project.name = form.name.data
        project.welcome = form.welcome.data 
        project.unknown = form.unknown.data 
        
        if form.bot_avatar.data:
            bot_avatar = form.bot_avatar.data
            ext = os.path.splitext(bot_avatar.filename)[1]
            filename = os.path.join(current_app.config['AVATAR_PATH'], "bot_{}{}".format(project_id, ext))
            bot_avatar.save(filename)
            project.bot_avatar = filename
        
        if form.user_avatar.data:
            user_avatar = form.user_avatar.data
            ext = os.path.splitext(user_avatar.filename)[1]
            filename = os.path.join(current_app.config['AVATAR_PATH'], "user_{}{}".format(project_id, ext))
            user_avatar.save(filename)
            project.user_avatar = filename

        db.session.commit()
        flash('项目设置修改成功', 'success')
        render_template('project/config.html', project_id=project_id, form=form)
    return render_template('project/config.html', project_id=project_id, form=form)
    
@project_bp.route('<int:project_id>/get_bot_avatar', methods=['GET'])
def get_bot_avatar(project_id):
    project = Project.query.get_or_404(project_id)
    return send_file(os.path.join(current_app.config['AVATAR_PATH'], project.bot_avatar))

@project_bp.route('<int:project_id>/get_user_avatar', methods=['GET'])
def get_user_avatar(project_id):
    project = Project.query.get_or_404(project_id)
    return send_file(os.path.join(current_app.config['AVATAR_PATH'], project.user_avatar))

@project_bp.route('<int:project_id>/deploy', methods=['GET'])
def deploy(project_id):
    return render_template('project/deploy.html',project_id=project_id)

botbase/templates/project/_base.html
{% extends 'base.html' %} {% block sidebar %}
<div class="side-nav expand-lg">
    <div class="side-nav-inner">
        <ul class="side-nav-menu">
            <li class="side-nav-header">
                <a href="{{url_for('front.panel')}}">
                    <i class="lni-chevron-left"></i>
                    <span>返回项目列表 </span>
                </a>

            </li>
            <li class="nav-item dropdown open">
                <a href="#" class="dropdown-toggle">
                    <span class="icon-holder">
            <i class="lni-dashboard"></i>
        </span>
                    <span class="title">机器人管理</span>
                    <span class="arrow">
            <i class="lni-chevron-right"></i>
        </span>
                </a>
                <ul class="dropdown-menu sub-down">
                    <li class="active">
                        <a href="{{url_for('project.index', project_id=project_id)}}">机器人列表</a>
                    </li>
                    <li>
                        <a href="{{url_for('project.create_bot', project_id=project_id)}}">新建机器人</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="#">
                    <span class="icon-holder">
            <i class="lni-layout"></i>
        </span>
                    <span class="title">Dashboard</span>
                    <span class="arrow">
            <i class="lni-chevron-right"></i>
        </span>
                </a>
                <ul class="dropdown-menu sub-down">
                    <li>
                        <a href="email.html">Dashboard1</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="#">
                    <span class="icon-holder">
            <i class="lni-paint-roller"></i>
        </span>
                    <span class="title">项目设置</span>
                    <span class="arrow">
            <i class="lni-chevron-right"></i>
        </span>
                </a>
                <ul class="dropdown-menu sub-down">
                    <li>
                        <a href="{{url_for('project.config',project_id=project_id)}}">基本设置</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="#">
                    <span class="icon-holder">
            <i class="lni-eye"></i>
        </span>
                    <span class="title">发布</span>
                    <span class="arrow">
            <i class="lni-chevron-right"></i>
        </span>
                </a>
                <ul class="dropdown-menu sub-down">
                    <li>
                        <a href="{{url_for('project.deploy', project_id=project_id)}}">测试链接</a>
                    </li>
                </ul>
            </li>


        </ul>
    </div>
</div>
{%endblock%}

botbase/templates/project/config.html
{% extends 'project/_base.html' %} {% from 'bootstrap/form.html' import render_form %} {% block title %}项目基本参数{% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-1-12">
            <h1>
                项目参数设置
            </h1>
        </div>

    </div>
</div>
<div class="container">

    <div class="row">
        <div class="col-8">
            <div class="card h-100">
                <div class="card-body">
                    {{ render_form(form, extra_classes='col-6') }}
                </div>

            </div>

        </div>
        <div class="col-lg-4">
            <div class="card h-100">
                <div class="card-body">
                    <h4>
                        当前机器人头像
                    </h4>
                    <img src="{{url_for('project.get_bot_avatar', project_id=project_id)}}" class="img-fluid" width="40px" alt="">
                    <h4>
                        当前用户头像
                    </h4>
                    <img src="{{url_for('project.get_user_avatar', project_id=project_id)}}" class="img-fluid" width="40px" alt="">

                </div>

            </div>
        </div>

    </div>
</div>
{% endblock%}

botbase/templates/project/create_bot.html
{% extends 'project/_base.html' %} {% from 'bootstrap/form.html' import render_form %} {% block title %}新建机器人{% endblock %} {% block content %}
<div class="container h-100">
    <div class="row h-100 page-header justify-content-center align-items-center">
        <h1>新建机器人</h1>
    </div>
    <div class="row h-100 justify-content-center align-items-center">
        {{ render_form(form, extra_classes='col-6') }}
    </div>
</div>
{% endblock content%}

botbase/templates/project/deploy.html
{% extends 'project/_base.html' %} {% from 'bootstrap/form.html' import render_form %} {% block title %}发布机器人{% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header border-bottom">
                    <h3>
                        发布测试链接
                        <a name="" id="" class="btn btn-primary float-right" href="#" role="button">应用当前修改</a>

                    </h3>

                </div>
                <div class="card-body">
                    <h4>当前chatbot生成时间</h4>
                    <p>2020.02.02 18:31</p>
                    <h4>
                        ChatBot链接:
                    </h4>
                    <p>
                        <a href="{{url_for('chat.chat', project_id=project_id)}}" target=" _blank ">
                            {{url_for('chat.chat', project_id=project_id, _external=True)}}
                        </a>
                    </p>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content%}

botbase/templates/project/index.html
{% extends 'project/_base.html' %} {% block title %}机器人列表{% endblock %} {% block content %}
<div class="container-fluid">
    <div class="breadcrumb-wrapper row">
        <div class="col-12 col-lg-3 col-md-6">
            <h4 class="page-title">机器人列表</h4>
        </div>
        <!-- <div class="col-12 col-lg-9 col-md-6">
            <ol class="breadcrumb float-right">
                <li><a href="index.html">机器人管理</a></li>
                <li class="active"> / 机器人列表</li>
            </ol>
        </div> -->
    </div>
    <div class="container-fluid">
        <div class="row">
            {% if bots %} {% for bot in bots %}
            <div class="col-md-12 col-xl-4">
                <div class="card h-100">
                    <div class="card-body">
                        <a href="{{url_for('bot.qa', project_id=project_id, bot_id=bot.id)}}">
                            <h5 class="card-title">{{bot.name}}</h5>
                            <p class="card-text">{{bot.area}}</p>
                        </a>

                        <a>
                            <form style="display: inline;" class="inline" method="POST" action="{{url_for('project.delete_bot',project_id=project_id,bot_id=bot.id)}}">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token()}}" />
                                <button type="submit" class="btn btn-danger btn-sm float-right" onclick="return confirm('确定删除该Bot？（删除后所有数据将会清空）')">Delete</button>
                            </form>
                        </a>

                    </div>
                </div>
            </div>
            {%endfor%} {%endif %}
            <div class="col-md-12 col-xl-4">
                <div class="card h-100">
                    <div class="card-body">
                        <a href="{{url_for('project.create_bot',project_id=project_id)}}">

                            <h5 class="card-title"> + </h5>
                            <p class="card-text">新建机器人</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content%}