botbase/blueprints/bot.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request, current_app, Blueprint, send_from_directory, request
from flask_login import login_required, current_user

from botbase.models import User, Project, Bot, QASet, SynWord, StopWord, QABot
from botbase.forms import ProjectForm, BotForm, QAForm, UploadQAForm, SynWordForm, StopWordForm, QABotBasicForm
from botbase.extensions import db
from botbase.utils.flask_tool import redirect_back
from botbase.decorators import admin_required, only_owner_can

from xlrd import open_workbook

import re

bot_bp = Blueprint('bot', __name__)

# @bot_bp.route("/<int:project_id>/<int:bot_id>", methods=['GET','POST'])
# @only_owner_can
# @login_required
# def index(project_id, bot_id):
#     return render_template('bot/index.html',project_id=project_id, bot_id=bot_id)

@bot_bp.route("/<int:project_id>/<int:bot_id>", methods=['GET','POST'])
@bot_bp.route("<int:project_id>/<int:bot_id>/qa", methods=['GET','POST'])
@only_owner_can
@login_required
def qa(project_id, bot_id):
    page = request.args.get('page', default=1, type=int)
    per_page = current_app.config['QA_PER_PAGE']
    pagination = QASet.query.filter_by(bot_id=bot_id).paginate(page, per_page=per_page)
    qa_set = pagination.items
    return render_template('bot/qa.html', project_id=project_id, bot_id=bot_id, pagination=pagination, qa_set=qa_set)

@bot_bp.route('<int:project_id>/<int:bot_id>/add_qa', methods=['GET', 'POST'])
@only_owner_can
@login_required
def add_qa(project_id, bot_id):
    form=QAForm()
    if form.validate_on_submit():
        q = form.question.data 
        a = form.answer.data 
        t = form.topic.data 
        qa = QASet(
            question=q,
            answer=a,
            topic=t,
            bot_id=bot_id
        )
        db.session.add(qa)
        db.session.commit()
        flash("新的问题添加成功", "success")
        return redirect(url_for('bot.qa', project_id=project_id, bot_id=bot_id))
    return render_template('bot/add_qa.html', form=form, project_id=project_id, bot_id=bot_id)


@bot_bp.route('<int:project_id>/<int:bot_id>/<int:qa_id>/delete_qa', methods=['POST'])
@only_owner_can
@login_required
def delete_qa(project_id, bot_id, qa_id):
    qa = QASet.query.get_or_404(qa_id)
    db.session.delete(qa)
    db.session.commit()
    flash('该问答对已删除', 'success')
    return redirect_back()

# TODO 改为模态框实现 可能需要js协助
@bot_bp.route('<int:project_id>/<int:bot_id>/<int:qa_id>/edit_qa', methods=['GET', 'POST'])
@only_owner_can
@login_required
def edit_qa(project_id, bot_id, qa_id):
    qa_set = QASet.query.get(qa_id)

    form = QAForm(
        question=qa_set.question,
        answer=qa_set.answer,
        topic=qa_set.topic)
    form.submit.label.text = "保存"

    if form.validate_on_submit():
        qa_set.answer=form.answer.data
        qa_set.question=form.question.data 
        qa_set.topic=form.topic.data 
        db.session.commit()
        flash('问题修改成功', 'success')
        return redirect(url_for('bot.qa', project_id=project_id, bot_id=bot_id))
    return render_template('bot/edit_qa.html', project_id=project_id, bot_id=bot_id, qa_id=qa_id, form=form)

@bot_bp.route('<int:project_id>/<int:bot_id>/upload_qa', methods=['GET', 'POST'])
@only_owner_can
@login_required
def upload_qa(project_id, bot_id):
    form = UploadQAForm()

    if form.validate_on_submit():
        qa_set = form.qa_set.data
        cover = form.cover.data 
        update_cnt = 0
        add_cnt = 0
        workbook = open_workbook(file_contents=qa_set.read())
        
        if cover:
            qas = QASet.query.filter_by(bot_id=bot_id).all()
            for _ele in qas:
                db.session.delete(_ele)
        try:
            for table in workbook.sheets():
                qs = table.col_values(0)
                ans = table.col_values(1)
                ts = table.col_values(2)
                for i in range(1, min([len(qs), len(ans), len(ts)])):
                    _qa = QASet.query.filter_by(bot_id=bot_id).filter_by(question=qs[i]).first()
                    if _qa:
                        _qa.answer=ans[i]
                        _qa.topic=ts[i]
                        db.session.commit()
                        update_cnt+=1
                    else:
                        _qa = QASet(
                            question=qs[i],
                            answer=ans[i],
                            topic=ts[i],
                            bot_id=bot_id
                        )
                        db.session.add(_qa)
                        add_cnt += 1
            db.session.commit()
            flash('成功上传{}个问答对, 增加了{}条，更新了{}条'.format(add_cnt+update_cnt, add_cnt, update_cnt), 'success')
            return redirect(url_for('bot.qa', project_id=project_id, bot_id=bot_id)) 
        except Exception as e:
            flash('上传错误，报错为: {}'.format(e), 'danger')
            return render_template('bot/upload_qa.html',form=form, project_id=project_id, bot_id=bot_id)
           
    return render_template('bot/upload_qa.html',form=form, project_id=project_id, bot_id=bot_id)
    

@bot_bp.route("<int:project_id>/<int:bot_id>/synword", methods=['GET','POST'])
@only_owner_can
@login_required
def synword(project_id, bot_id):
    page = request.args.get('page', default=1, type=int)
    per_page = current_app.config['QA_PER_PAGE']
    pagination = SynWord.query.filter_by(bot_id=bot_id).paginate(page, per_page=per_page)
    synwords = pagination.items
    return render_template('bot/synword.html', project_id=project_id, bot_id=bot_id, pagination=pagination, synwords=synwords)

@bot_bp.route('<int:project_id>/<int:bot_id>/add_synword', methods=['GET', 'POST'])
@only_owner_can
@login_required
def add_synword(project_id, bot_id):
    form=SynWordForm()
    if form.validate_on_submit():
        b = form.base_word.data 
        s = form.synword.data 
        syn = SynWord(
            base_word=b,
            syn_word=s,
            bot_id=bot_id
        )
        db.session.add(syn)
        db.session.commit()
        flash("新的近义词组添加成功", "success")
        return redirect(url_for('bot.synword', project_id=project_id, bot_id=bot_id))
    return render_template('bot/add_synword.html', form=form, project_id=project_id, bot_id=bot_id)

@bot_bp.route('<int:project_id>/<int:bot_id>/<int:synword_id>/delete_synword', methods=['POST'])
@only_owner_can
@login_required
def delete_synword(project_id, bot_id, synword_id):
    synword = SynWord.query.get_or_404(synword_id)
    db.session.delete(synword)
    db.session.commit()
    flash('该同义词集已删除', 'success')
    return redirect_back()

@bot_bp.route('<int:project_id>/<int:bot_id>/<int:synword_id>/edit_synword', methods=['GET', 'POST'])
@only_owner_can
@login_required
def edit_synword(project_id, bot_id, synword_id):
    synword = SynWord.query.get_or_404(synword_id)

    form = SynWordForm(
        base_word=synword.base_word,
        synword=synword.syn_word)
    form.submit.label.text = "保存"

    if form.validate_on_submit():
        synword.base_word=form.base_word.data
        synword.syn_word=form.synword.data 
        db.session.commit()
        flash('问答对修改成功', 'success')
        return redirect(url_for('bot.synword', project_id=project_id, bot_id=bot_id))
    return render_template('bot/edit_synword.html', project_id=project_id, bot_id=bot_id, synword_id=synword_id, form=form)





@bot_bp.route("<int:project_id>/<int:bot_id>/stopword", methods=['GET','POST'])
@only_owner_can
@login_required
def stopword(project_id, bot_id):
    page = request.args.get('page', default=1, type=int)
    per_page = current_app.config['QA_PER_PAGE']
    pagination = StopWord.query.filter_by(bot_id=bot_id).paginate(page, per_page=per_page)
    stopword = pagination.items
    return render_template('bot/stopword.html', project_id=project_id, bot_id=bot_id, pagination=pagination, stopword=stopword)

@bot_bp.route('<int:project_id>/<int:bot_id>/add_stopword', methods=['GET', 'POST'])
@only_owner_can
@login_required
def add_stopword(project_id, bot_id):
    form=StopWordForm()
    if form.validate_on_submit():
        s = form.word.data 
        word=re.split(",|，", s)
        for w in word:
            _stopword = StopWord(
                word=w.strip(),
                bot_id=bot_id
            )
            db.session.add(_stopword)
        db.session.commit()
        flash("新的停用词添加成功", "success")
        return redirect(url_for('bot.stopword', project_id=project_id, bot_id=bot_id))
    return render_template('bot/add_stopword.html', form=form, project_id=project_id, bot_id=bot_id)

@bot_bp.route('<int:project_id>/<int:bot_id>/<int:stopword_id>/delete_stopword', methods=['POST'])
@only_owner_can
@login_required
def delete_stopword(project_id, bot_id, stopword_id):
    stopword = StopWord.query.get_or_404(stopword_id)
    db.session.delete(stopword)
    db.session.commit()
    flash('该停用词已删除', 'success')
    return redirect_back()

@bot_bp.route('<int:project_id>/<int:bot_id>/basic_config', methods=['GET', 'POST'])
@only_owner_can
@login_required
def qa_config(project_id, bot_id):
    qabot = QABot.query.filter_by(bot_id=bot_id).first()
    form = QABotBasicForm(
        name=qabot.name,
        th1=qabot.th1,
        th2=qabot.th2,
        k1=qabot.k1
    )
    if form.validate_on_submit():
        qabot.name = form.name.data 
        qabot.th1 = form.th1.data 
        qabot.th2 = form.th2.data 
        qabot.k1 = form.k1.data 
        db.session.commit()
        flash('机器人参数保存成功', 'success')
        return render_template('bot/config.html', project_id=project_id, bot_id=bot_id, form=form)
    return render_template('bot/config.html', project_id=project_id, bot_id=bot_id, form=form)

botbase/templates/bot/_base.html
{% extends 'base.html' %} {% block sidebar %}
<div class="side-nav expand-lg">
    <div class="side-nav-inner">
        <ul class="side-nav-menu">
            <li class="side-nav-header">
                <span>
                    <a href="{{url_for('project.index', project_id=project_id)}}">
                       返回机器人列表
                    </a> 
                </span>


            </li>
            <li class="nav-item dropdown open">
                <a href="#" class="dropdown-toggle">
                    <span class="icon-holder">
            <i class="lni-dashboard"></i>
        </span>
                    <span class="title">知识库管理</span>
                    <span class="arrow">
            <i class="lni-chevron-right"></i>
        </span>
                </a>
                <ul class="dropdown-menu sub-down">
                    <li {%if active=="qa" %} class="active" {%endif%}>
                        <a href="{{url_for('bot.qa', project_id=project_id, bot_id=bot_id)}}">问答集</a>
                    </li>
                    <li {%if active=="synword" %} class="active" {%endif%}>
                        <a href="{{url_for('bot.synword', project_id=project_id, bot_id=bot_id)}}">同义词</a>
                    </li>
                    <li {%if active=="stopword" %} class="active" {%endif%}>
                        <a href="{{url_for('bot.stopword', project_id=project_id, bot_id=bot_id)}}">停用词</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown open">
                <a class="dropdown-toggle" href="#">
                    <span class="icon-holder">
            <i class="lni-cloud"></i>
        </span>
                    <span class="title">机器人配置</span>
                    <span class="arrow">
            <i class="lni-chevron-right"></i>
        </span>
                </a>
                <ul class="dropdown-menu sub-down">
                    <li {%if active=="config" %} class="active" {%endif%}>
                        <a href="{{url_for('bot.qa_config', project_id=project_id, bot_id=bot_id)}}">基本参数</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
{%endblock%}

botbase/templates/bot/add_qa.html
{% extends 'bot/_base.html' %} {% from 'bootstrap/form.html' import render_form %} {% block title %}添加问答对{% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-1-12">
            <h1>
                添加问答对
            </h1>
        </div>

    </div>
</div>
<div class="container">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    {{ render_form(form, extra_classes='col-6') }}
                </div>

            </div>

        </div>

    </div>
</div>
{% endblock%}

botbase/templates/bot/add_stopword.html
{% extends 'bot/_base.html' %} {% from 'bootstrap/form.html' import render_form %} {% block title %}添加停用词{% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-1-12">
            <h1>
                添加停用词
            </h1>
        </div>

    </div>
</div>
<div class="container">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <p>
                        多个词之间请用“，”分割
                    </p>
                </div>
                <div class="card-body">
                    {{ render_form(form, extra_classes='col-6') }}
                </div>

            </div>

        </div>

    </div>
</div>
{% endblock%}

botbase/templates/bot/add_synword.html
{% extends 'bot/_base.html' %} {% from 'bootstrap/form.html' import render_form %} {% block title %}添加近义词组{% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-1-12">
            <h1>
                添加近义词组
            </h1>
        </div>

    </div>
</div>
<div class="container">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    {{ render_form(form, extra_classes='col-6') }}
                </div>

            </div>

        </div>

    </div>
</div>
{% endblock%}

botbase/templates/bot/config.html
{% extends 'bot/_base.html' %}{%set active="config"%} {% from 'bootstrap/form.html' import render_form %} {% block title %}修改问答对{% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-1-12">
            <h1>
                机器人参数设置
            </h1>
        </div>

    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    {{ render_form(form, extra_classes='col-6') }}
                </div>

            </div>

        </div>

    </div>
</div>
{% endblock%}

botbase/templates/bot/edit_qa.html
{% extends 'bot/_base.html' %} {% from 'bootstrap/form.html' import render_form %} {% block title %}修改问答对{% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-1-12">
            <h1>
                修改问答对
            </h1>
        </div>

    </div>
</div>
<div class="container">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    {{ render_form(form, extra_classes='col-6') }}
                </div>

            </div>

        </div>

    </div>
</div>
{% endblock%}

botbase/templates/bot/edit_synword.html
{% extends 'bot/_base.html' %} {% from 'bootstrap/form.html' import render_form %} {% block title %}修改同义词对{% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-1-12">
            <h1>
                修改同义词对
            </h1>
        </div>

    </div>
</div>
<div class="container">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    {{ render_form(form, extra_classes='col-6') }}
                </div>

            </div>

        </div>

    </div>
</div>
{% endblock%}

botbase/templates/bot/index.html
{% extends 'bot/_base.html' %}

{% block content %}
<h1>This is a bot</h1>
{% endblock%}

botbase/templates/bot/qa.html
{% extends 'bot/_base.html' %} {%set active="qa"%} {% block content %} {% from 'bootstrap/pagination.html' import render_pagination %}
<div class="container">
    <div class="row">
        <div class="col-lg-1-12">
            <h1>
                问答集管理
            </h1>
        </div>

    </div>
</div>

<!-- <div class="container">
    <div class="row">
        <div class="col-lg-8">
        </div>
        <div class="col-lg-4">
            <a name="" id="" style="margin:5px" class="btn btn-common" href="{{url_for('bot.add_qa', project_id=project_id, bot_id=bot_id)}}" role="button">
                + 添加问答对
            </a>
            <a name="" id="" class="btn btn-primary" href="#" role="button">从文件中导入</a>
        </div>
    </div>
</div> -->

<div class="container">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header border-bottom">
                    <a name="" id="" style="margin:5px" class="btn btn-common" href="{{url_for('bot.add_qa', project_id=project_id, bot_id=bot_id)}}" role="button">
                            + 添加问答对
                        </a>
                    <a name="" id="" class="btn btn-primary" href="{{url_for('bot.upload_qa', project_id=project_id, bot_id=bot_id)}}" role="button">从文件中导入</a>
                    <!-- <a name="" id="" class="btn btn-primary" href="#" role="button">从txt中导入</a> -->
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>id</th>
                                    <th>问题</th>
                                    <th>答案</th>
                                    <th>类别</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            {% for qa in qa_set%} {% if qa.question%}
                            <tr>
                                <td scope="row">{{qa.id}}</td>
                                <td>{{qa.question}}</td>
                                <td>{{qa.answer}}</td>
                                <td>{{qa.topic}}</td>
                                <td>
                                    <a name="" id="" class="btn btn-info btn-sm " href="{{url_for('bot.edit_qa', project_id=project_id, bot_id=bot_id, qa_id=qa.id)}}" role="button">Edit</a>
                                    <form class="inline" style="display:inline" method="POST" action="{{url_for('bot.delete_qa', qa_id=qa.id, project_id=project_id, bot_id=bot_id)}}">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token()}}" />
                                        <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('确定删除该问答对？')">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            {%endif%} {%endfor%}
                        </table>
                        {{render_pagination(pagination)}}

                    </div>
                </div>

            </div>

        </div>

    </div>
</div>



{% endblock content%}

botbase/templates/bot/stopword.html
{% extends 'bot/_base.html' %} {%set active="stopword"%}{% block content %} {% from 'bootstrap/pagination.html' import render_pagination %}
<div class="container">
    <div class="row">
        <div class="col-lg-1-12">
            <h1>
                停用词管理
            </h1>
        </div>

    </div>
</div>


<div class="container">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header border-bottom">
                    <a name="" id="" style="margin:5px" class="btn btn-common" href="{{url_for('bot.add_stopword', project_id=project_id, bot_id=bot_id)}}" role="button">
                            + 添加停用词
                        </a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>id</th>
                                    <th>停用词</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            {% for word in stopword%} {% if word.word%}
                            <tr>
                                <td scope="row">{{word.id}}</td>
                                <td>{{word.word}}</td>
                                <td>
                                    <form class="inline" style="display:inline" method="POST" action="{{url_for('bot.delete_stopword', stopword_id=word.id, project_id=project_id, bot_id=bot_id)}}">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token()}}" />
                                        <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('确定删除该停用词?')">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            {%endif%} {%endfor%}
                        </table>
                        {{render_pagination(pagination)}}

                    </div>
                </div>

            </div>

        </div>

    </div>
</div>



{% endblock content%}

botbase/templates/bot/synword.html
{% extends 'bot/_base.html' %} {%set active="synword"%}{% block content %} {% from 'bootstrap/pagination.html' import render_pagination %}
<div class="container">
    <div class="row">
        <div class="col-lg-1-12">
            <h1>
                近义词管理
            </h1>
        </div>

    </div>
</div>


<div class="container">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header border-bottom">
                    <a name="" id="" style="margin:5px" class="btn btn-common" href="{{url_for('bot.add_synword', project_id=project_id, bot_id=bot_id)}}" role="button">
                            + 添加近义词
                        </a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>id</th>
                                    <th>原词</th>
                                    <th>近义词</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            {% for word in synwords%} {% if word.base_word%}
                            <tr>
                                <td scope="row">{{word.id}}</td>
                                <td>{{word.base_word}}</td>
                                <td>{{word.syn_word}}</td>
                                <td>
                                    <a name="" id="" class="btn btn-info btn-sm " href="{{url_for('bot.edit_synword', synword_id=word.id, project_id=project_id, bot_id=bot_id)}}" role="button">Edit</a>
                                    <form class="inline" style="display:inline" method="POST" action="{{url_for('bot.delete_synword', synword_id=word.id, project_id=project_id, bot_id=bot_id)}}">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token()}}" />
                                        <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('确定删除该近义词组?')">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            {%endif%} {%endfor%}
                        </table>
                        {{render_pagination(pagination)}}

                    </div>
                </div>

            </div>

        </div>

    </div>
</div>



{% endblock content%}

botbase/templates/bot/upload_qa.html
{% extends 'bot/_base.html' %} {% from 'bootstrap/form.html' import render_form %} {% block title %}上传问答集{% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-1-12">
            <h1>
                上传问答集
            </h1>
        </div>

    </div>
</div>
<div class="container">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header border-bottom">
                    <p>仅支持xlsx格式的上传。上传文件需为三列，分别为：问题，答案，类别。模板文件可从下方下载。</p>
                    <a name="" id="" class="btn btn-inverse-primary btn-sm" href="#" role="button">模板下载</a>
                </div>
                <div class="card-body">
                    {{ render_form(form, extra_classes='col-6') }}
                </div>

            </div>

        </div>

    </div>
</div>
{% endblock%}