botbase/blueprints/front.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request, current_app, Blueprint, send_from_directory
from flask_login import login_user, logout_user, login_required, current_user

from botbase.models import User, Project
from botbase.forms import ProjectForm, LoginForm
from botbase.extensions import db
from botbase.utils.flask_tool import redirect_back
from botbase.decorators import only_owner_can

front_bp = Blueprint('front', __name__)

@front_bp.route('/', methods=['GET', 'POST'])
def index():
    if current_user.is_authenticated:
        return redirect(url_for('front.panel'))
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data 
        password = form.password.data 
        remember = form.remember_me.data 
        user = User.query.filter_by(username=username.lower()).first()

        if user is not None and user.validate_password(password):
            login_user(user, remember)
            # print(current_user.is_admin)
            flash('welcome back', 'info')
            return redirect(url_for('front.panel'))
        else:
            flash('无效的账户或密码', 'warning')
            return redirect(url_for('front.index'))
    return render_template('index.html', form=form)

@front_bp.route('/panel')
@login_required
def panel():
    projects = Project.query.filter_by(user_id=current_user.id).all()
    return render_template('front/panel.html', projects=projects)

@front_bp.route('/create_project', methods=['GET', 'POST'])
@login_required
def create_project():
    form = ProjectForm()
    if form.validate_on_submit():
        name = form.name.data
        area = form.area.data 
        user_id = current_user.id
        project = Project(name=name, area=area, user_id=current_user.id)
        db.session.add(project)
        db.session.commit()
        return redirect(url_for('front.panel'))
    return render_template('front/create_project.html', form=form)

@front_bp.route('/project/<int:project_id>/delete', methods=['POST'])
@only_owner_can
@login_required
def delete_project(project_id):
    project = Project.query.get_or_404(project_id)
    db.session.delete(project)
    db.session.commit()
    flash('Project deleted.', 'success')
    return redirect_back()

botbase/templates/front/_base.html
{% extends 'base.html' %} {% block sidebar %}
<div class="side-nav expand-lg">
    <div class="side-nav-inner">
        <ul class="side-nav-menu">
            <li class="side-nav-header">
                <i class="lni-laptop"></i>
                <!-- <span>Navigation</span> -->
            </li>
            <li class="nav-item dropdown open">
                <a href="#" class="dropdown-toggle">
                    <span class="icon-holder">
            <i class="lni-dashboard"></i>
        </span>
                    <span class="title">项目列表</span>
                    <span class="arrow">
            <i class="lni-chevron-right"></i>
        </span>
                </a>
                <ul class="dropdown-menu sub-down">
                    <li class="active">
                        <a href="{{url_for('front.panel')}}">项目列表</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="#">
                    <span class="icon-holder">
            <i class="lni-cloud"></i>
        </span>
                    <span class="title">帮助</span>
                    <span class="arrow">
            <i class="lni-chevron-right"></i>
        </span>
                </a>
                <ul class="dropdown-menu sub-down">
                    <li>
                        <a href="#">视频教程</a>
                    </li>
                    <li>
                        <a href="#">文档</a>
                    </li>
                    <li>
                        <a href="#">联系专家</a>
                    </li>
                </ul>
            </li>
            {% if current_user.is_admin%}
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="#">
                    <span class="icon-holder">
            <i class="lni-cloud"></i>
        </span>
                    <span class="title">用户管理</span>
                    <span class="arrow">
            <i class="lni-chevron-right"></i>
        </span>
                </a>
                <ul class="dropdown-menu sub-down">
                    <li>
                        <a href="{{url_for('admin.user_manage')}}">用户列表</a>
                    </li>
                </ul>
            </li>
            {% endif%}
        </ul>
    </div>
</div>
{%endblock%}

botbase/templates/front/create_project.html
{% extends 'front/_base.html' %} {% from 'bootstrap/form.html' import render_form %} {% block title %}新建项目{% endblock %} {% block content %}
<div class="container h-100">
    <div class="row h-100 page-header justify-content-center align-items-center">
        <h1>新建项目</h1>
    </div>
    <div class="row h-100 justify-content-center align-items-center">
        {{ render_form(form, extra_classes='col-6') }}
    </div>
</div>
{% endblock content%}

botbase/templates/front/index.html
{% extends 'base.html' %}

{% block title %}主页{% endblock %}

{% block content %}
<h1>
    Welcome use D.Bot. This Front Index
</h1>
{% endblock content%}

botbase/templates/front/panel.html
{% extends 'front/_base.html' %} {% block title %}项目面板{% endblock %} {% block content %}
<div class="container-fluid">
    <div class="breadcrumb-wrapper row">
        <div class="col-12 col-lg-3 col-md-6">
            <h4 class="page-title">项目列表</h4>
        </div>
        <!-- <div class="col-12 col-lg-9 col-md-6">
            <ol class="breadcrumb float-right">
                <li><a href="index.html">机器人管理</a></li>
                <li class="active"> / 机器人列表</li>
            </ol>
        </div> -->
    </div>
    <div class="container-fluid">
        <div class="row">
            {% if projects %} {% for project in projects %}
            <div class="col-md-12 col-xl-4">
                <div class="card h-100">
                    <div class="card-body">
                        <a href="{{url_for('project.index', project_id=project.id)}}">
                            <h5 class="card-title">{{project.name}}</h5>
                            <p class="card-text">{{project.area}}</p>
                        </a>

                        <a>
                            <form style="display: inline;" class="inline" method="POST" action="{{url_for('front.delete_project',project_id=project.id)}}">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token()}}" />
                                <button type="submit" class="btn btn-danger btn-sm float-right" onclick="return confirm('确定删除该项目？（删除后所有数据将会清空）')">Delete</button>
                            </form>
                        </a>

                    </div>
                </div>
            </div>
            {%endfor%} {%endif %}
            <div class="col-md-12 col-xl-4">
                <div class="card h-100">
                    <div class="card-body">
                        <a href="{{url_for('front.create_project')}}">

                            <h5 class="card-title"> + </h5>
                            <p class="card-text">新建项目</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content%}