botbase/blueprints/auth.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user

from botbase.forms import LoginForm, TrialForm
from botbase.models import User

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('front.index'))
    
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data 
        password = form.password.data 
        remember = form.remember_me.data 
        user = User.query.filter_by(username=username.lower()).first()

        if user is not None and user.validate_password(password):
            login_user(user, remember)
            # print(current_user.is_admin)
            flash('welcome back', 'info')
            return redirect(url_for('front.panel'))
        else:
            flash('无效的账户或密码', 'warning')
            return redirect(url_for('auth.login'))
    return render_template('auth/login.html', form=form)

@auth_bp.route('/logout')
def logout():
    logout_user()
    #flash('Logout success.', 'info')
    return redirect(url_for('front.index'))

@auth_bp.route('/trial', methods=['GET', 'POST'])
def trial():
    form = TrialForm()
    if form.validate_on_submit():
        flash("您的申请已发送，请等待回复", 'success')
        return redirect(url_for('front.index'))
    return render_template('trial.html', form=form)

botbase/templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">

<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {%block title%} {%endblock title%} D.Bot
    </title>
    <link rel="icon" href="{{url_for('static', filename='favicon.ico')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/fonts/line-icons.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='vendor/plugins/morris/morris.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/css/main.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/css/responsive.css')}}"> {%endblock head%}
</head>

<body>
    <div class="app header-default side-nav-dark">
        <div class="layout">
            <div class="header navbar">
                <div class="header-container">
                    <div class="nav-logo">
                        <a href="{{url_for('front.panel')}}">
                            <b><img src="{{url_for('static', filename='vendor/img/dbot_logo.png')}}" height="34px" alt=""></b>
                            <span class="logo">
                                <img src="{{url_for('static', filename='vendor/img/dbot_logo_text.png')}}" height="34px" alt="">
                            </span>
                        </a>
                    </div>
                    <ul class="nav-left">
                        <li>
                            <a class="sidenav-fold-toggler" href="javascript:void(0);">
                                <i class="lni-menu"></i>
                            </a>
                            <a class="sidenav-expand-toggler" href="javascript:void(0);">
                                <i class="lni-menu"></i>
                            </a>
                        </li>
                    </ul>

                    <ul class="nav-right">
                        {% if not current_user.is_authenticated%}
                        <li>
                            <a href="{{url_for('auth.login')}}">
                                <button type="button" class="btn btn-common">
                                    登录
                                </button>
                            </a>

                        </li>
                        <li>
                            <a href="{{url_for('auth.trial')}}">
                                <button type="button" class="btn btn-primary">
                                    申请试用
                                </button>
                            </a>

                        </li>
                        {%else%}

                        <li class="user-profile dropdown dropdown-animated scale-left">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img class="profile-img img-fluid" src="{{url_for('static', filename='vendor/img/avatar/avatar.jpg')}}" alt="">
                            </a>
                            <ul class="dropdown-menu dropdown-md">
                                <li>
                                    <ul class="list-media">
                                        <li class="list-item avatar-info">
                                            <div class="media-img">
                                                <img src="{{url_for('static', filename='vendor/img/avatar/avatar.jpg')}}" alt="">
                                            </div>
                                            <a href="{{url_for('front.panel')}}">
                                                <div class="info">
                                                    <span class="title text-semibold">{{current_user.username}}</span>
                                                    <span class="sub-title">{{current_user.role.name}}</span>
                                                </div>
                                            </a>

                                        </li>
                                    </ul>
                                    <li>
                                        <li>
                                            <a href="{{url_for('auth.logout')}}">
                                                <i class="lni-lock"></i>
                                                <span>Logout</span>
                                            </a>
                                        </li>
                            </ul>
                            </li>
                            {%endif%}
                    </ul>
                </div>
            </div>

            <div class="swlink">Developed by DAI</div>
            {%block sidebar%} {%endblock sidebar%}


            <div class="page-container">
                <div class="main-content">
                    {% for message in get_flashed_messages(with_categories=True) %}
                    <div class="alert alert-{{ message[0] }}" role="alert">
                        <button type="button" class="close" data-dismiss="alert">&times;</button> {{ message[1] }}
                    </div>
                    {% endfor %} {%block content%} {%endblock content%}
                </div>


                <footer class="content-footer">
                    <div class="footer">
                        <div class="copyright">
                            <span>Copyright © 2018 <b class="text-dark">DAI</b>. All Right Reserved.</span>

                        </div>
                    </div>
                </footer>

            </div>

        </div>
    </div>

    <div id="preloader">
        <div class="loader" id="loader-1"></div>
    </div>


    <script src="{{url_for('static', filename='vendor/js/jquery-min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/popper.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/jquery.app.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/main.js')}}"></script>

    <script src="{{url_for('static', filename='vendor/plugins/morris/morris.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/plugins/raphael/raphael-min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/dashborad1.js')}}"></script>
</body>

</html>

botbase/templates/index.html
{% from 'bootstrap/form.html' import render_form %}

<!DOCTYPE html>
<html>

<!-- source http://www.scnoob.com More templates http://www.scnoob.com/moban -->

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>D.Bot</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/fonts/line-icons.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='vendor/plugins/morris/morris.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/css/main.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/css/responsive.css')}}">
    <link href="{{url_for('static', filename='vendor/css/signin.css')}}" rel="stylesheet">
</head>

<!-- <body class="text-center" data-gr-c-s-loaded="true" style="background-image: url({{url_for('static', filename='vendor/img/index.png')}});background-size: cover;">
    <div class="container-fluid">
        <div class="row">
            <nav class="navbar navbar-default navbar-static-top" role="navigation">
                <div class="nav-logo">
                    <a href="{{url_for('front.panel')}}">
                        <b><img src="{{url_for('static', filename='vendor/img/dbot_logo.png')}}" height="34px" alt=""></b>
                        <span class="logo">
                                <img src="{{url_for('static', filename='vendor/img/dbot_logo_text.png')}}" height="34px" alt="">
                            </span>
                    </a>
                </div>

                <ul class="nav-right">
                    <li>
                        <a href="{{url_for('auth.trial')}}">
                            <button type="button float-right" class="btn btn-primary">
                                申请试用
                            </button>
                        </a>

                    </li>
                </ul>

            </nav>


        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="container h-100">
                <div class="row h-100 page-header justify-content-center align-items-center">
                    <img src="{{url_for('static', filename='vendor/img/dbot_logo.png')}}" height="68px" alt="">
                </div>
                <div class="row h-100 justify-content-center align-items-center">
                    {{ render_form(form, extra_classes='col-4') }}
                </div>
            </div>
        </div>

    </div>



    </div>

    </div>



    <div id="preloader">
        <div class="loader" id="loader-1"></div>
    </div>


    <script src="{{url_for('static', filename='vendor/js/jquery-min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/popper.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/jquery.app.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/main.js')}}"></script>

    <script src="{{url_for('static', filename='vendor/plugins/morris/morris.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/plugins/raphael/raphael-min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/dashborad1.js')}}"></script>
</body> -->

<!-- source http://www.scnoob.com More templates http://www.scnoob.com/moban -->

<body class="text-center" data-gr-c-s-loaded="true" style="background-image: url({{url_for('static', filename='vendor/img/index.png')}});background-size: cover;">

    <div class="container-fluid">
        <!-- <div class="row">
            <div class="col-lg-10">
            </div>
            <div class="col-lg-2">
                <a name="" id="" class="btn btn-warning" href="#" role="button">申请试用</a>
            </div>
        </div> -->{% for message in get_flashed_messages(with_categories=True) %}
        <div class="row">
            <div class="col-lg-4">
            </div>
            <div class="col-lg-4">
                <div class="alert alert-{{ message[0] }}" role="alert">
                    <button type="button" class="close" data-dismiss="alert">&times;</button> {{ message[1] }}
                </div>
            </div>
            <div class="col-lg-4">
            </div>
        </div>
        {% endfor %} {%block content%} {%endblock content%}
        <div class="row">
            <form class="form-signin" method="post">
                <img class="mb-4" src="{{url_for('static', filename='vendor/img/dbot_logo.png')}}" alt="" height="72">
                <h1 class="h3 mb-3 font-weight-normal">欢迎使用D.Bot</h1>
                {{form.csrf_token}} {{form.username.label(class="sr-only")}} {{form.username(class="form-control",placeholder="用户名")}} {{form.password.label(class='sr-only')}}{{form.password(class="form-control", placeholder="密码")}}
                <div class="checkbox mb-3">
                    {{form.remember_me}}{{form.remember_me.label}}
                </div>
                {{form.submit(class="btn btn-lg btn-primary btn-block")}}
                <a name="" id="" class="btn btn-lg btn-warning btn-block" href="{{url_for('auth.trial')}}" role="button">申请试用</a>
            </form>
        </div>

    </div>
    <script src="{{url_for('static', filename='vendor/js/jquery-min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/popper.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/jquery.app.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/main.js')}}"></script>

    <script src="{{url_for('static', filename='vendor/plugins/morris/morris.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/plugins/raphael/raphael-min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/dashborad1.js')}}"></script>
</body>

</html>

botbase/templates/trial.html
{% from 'bootstrap/form.html' import render_form %}

<!DOCTYPE html>
<html>

<!-- source http://www.scnoob.com More templates http://www.scnoob.com/moban -->

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>D.Bot</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/fonts/line-icons.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='vendor/plugins/morris/morris.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/css/main.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/css/responsive.css')}}">
    <link href="{{url_for('static', filename='vendor/css/signin.css')}}" rel="stylesheet">
</head>

<!-- <body class="text-center" data-gr-c-s-loaded="true" style="background-image: url({{url_for('static', filename='vendor/img/index.png')}});background-size: cover;">
    <div class="container-fluid">
        <div class="row">
            <nav class="navbar navbar-default navbar-static-top" role="navigation">
                <div class="nav-logo">
                    <a href="{{url_for('front.panel')}}">
                        <b><img src="{{url_for('static', filename='vendor/img/dbot_logo.png')}}" height="34px" alt=""></b>
                        <span class="logo">
                                <img src="{{url_for('static', filename='vendor/img/dbot_logo_text.png')}}" height="34px" alt="">
                            </span>
                    </a>
                </div>

                <ul class="nav-right">
                    <li>
                        <a href="{{url_for('auth.trial')}}">
                            <button type="button float-right" class="btn btn-primary">
                                申请试用
                            </button>
                        </a>

                    </li>
                </ul>

            </nav>


        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="container h-100">
                <div class="row h-100 page-header justify-content-center align-items-center">
                    <img src="{{url_for('static', filename='vendor/img/dbot_logo.png')}}" height="68px" alt="">
                </div>
                <div class="row h-100 justify-content-center align-items-center">
                    {{ render_form(form, extra_classes='col-4') }}
                </div>
            </div>
        </div>

    </div>



    </div>

    </div>



    <div id="preloader">
        <div class="loader" id="loader-1"></div>
    </div>


    <script src="{{url_for('static', filename='vendor/js/jquery-min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/popper.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/jquery.app.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/main.js')}}"></script>

    <script src="{{url_for('static', filename='vendor/plugins/morris/morris.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/plugins/raphael/raphael-min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/dashborad1.js')}}"></script>
</body> -->

<!-- source http://www.scnoob.com More templates http://www.scnoob.com/moban -->

<body class="text-center" data-gr-c-s-loaded="true" style="background-image: url({{url_for('static', filename='vendor/img/index.png')}});background-size: cover;">

    <!-- <form class="form-signin">
        <img class="mb-4" src="{{url_for('static', filename='vendor/img/dbot_logo.png')}}" alt="" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
        <div class="checkbox mb-3">
            <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted">© 2017-2019</p>
    </form> -->
    <div class="container-fluid">
        <!-- <div class="row">
            <div class="col-lg-10">
            </div>
            <div class="col-lg-2">
                <a name="" id="" class="btn btn-warning" href="#" role="button">申请试用</a>
            </div>
        </div> -->
        <div class="row">
            <form class="form-signin" method="post">
                <img class="mb-4" src="{{url_for('static', filename='vendor/img/dbot_logo.png')}}" alt="" height="72">
                <h1 class="h3 mb-3 font-weight-normal">请填写相关信息</h1>
                {{form.csrf_token}} {{form.email.label(class="sr-only")}} {{form.email(class="form-control",placeholder="邮箱")}} {{form.department.label(class='sr-only')}}{{form.department(class="form-control", placeholder="部门")}} {{form.reason.label(class='sr-only')}}{{form.reason(class="form-control",
                placeholder="业务场景")}} {{form.submit(class="btn btn-lg btn-warning btn-block")}}
            </form>
        </div>

    </div>
    <script src="{{url_for('static', filename='vendor/js/jquery-min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/popper.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/jquery.app.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/main.js')}}"></script>

    <script src="{{url_for('static', filename='vendor/plugins/morris/morris.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/plugins/raphael/raphael-min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/js/dashborad1.js')}}"></script>
</body>

</html>